### PR TITLE
Add config option for cgroups

### LINKED ISSUE #42: launch apps in cgroups
Hi, this would be a nice feature, as app detection in various task managers/system monitors rely on it to detect open windows, and their fallbacks are not reliable at all.

This would look like this:
```
systemd-run --scope --user --unit="app-[launcher-name]-[desktop-file-name]-[random-stuff]" [desktop-file-exec]
```
instead of just running the last part.

[launcher-name] would be sirula, [desktop-file-name] the .desktop file without the .desktop, and [random-stuff] is merely there to allow multiple instances of the app.\
gnome uses the pid of the app, while kde uses a full random uuid.

Here is a example for foot:
```
systemd-run --scope --user --unit="app-sirula-org.codeberg.dnkl.footclient-1234" footclient 
```

### PR DESCRIPTION
**Pull request by jlo62**
Adds the config option `cgroups = bool`

Resolves #42

### CODE REVIEW

**Comment by DorianRudolph** [comment]
hey, sorry for neglecting this project... do you want to become maintainer?

**Comment by jlo62** [comment]
> hey, sorry for neglecting this project... do you want to become maintainer?

I sadly do not fully understand programming GTK GUIs with rust, but I'd have the free time, and it's not that I can make matters a worse. It'd definitely be better than a orphaned project, so I could give it a go.
I have already tried to continue sirula [in my own branch](https://github.com/jlo62/sirula) and have simply merged most of the open MRs
Anyway thank you for writing a solid base! I find sirula quite useful.
\- Jan Luca

**Comment by DorianRudolph** [comment]
Ok, I sent you an invite. I would not worry about the GTK thing, this was my first GTK project as well. I still use sirula and just installed it on my new laptop and remembered that there were still a lot of open PRs.

**Comment by jlo62** [comment]
Thank you! I'll take care of the MRs soon (I've got an exam tomorrow, still gotta dump some stuff in my brain)

**Pull request merged**
