### PR TITLE
Change app icon loading to work well with high DPI

### PR DESCRIPTION
**Pull request by The0x539**
I've been searching for a sway-friendly app launcher I like for a while now, and this project has come the closest to satisfying my needs, with two caveats:

- app icons seem to be subjected to bilinear upscaling on high-DPI screens, even if the source file is an SVG
- sirula takes longer to open than sway-launcher-desktop, resulting in one or two of my keystrokes being premature

This patch fixes the former. I don't really have any prior experience with GTK or gtk-rs, so there might be a better way to do this, but this seems to at least work for me.

### CODE REVIEW

**Comment by DorianRudolph** [comment]
Thanks for your contribution. I never noticed because I don't have a HiDPI screen. I will take a look at the startup time.

**Comment by The0x539** [comment]
From what I've been able to figure out, it looks like a lot of the startup time is spent on GTK runtime stuff that I'm not sure is avoidable. I've tried to experiment with adding a "daemon mode" of sorts, but man, gtk-rs is complicated, and keeping track of whether the program is running in daemon mode without adding a global variable seems to require messing with inheritance and GObject, which does _not_ seem like fun.

**Comment by DorianRudolph** [comment]
I think you can use the startup handler (`connect_startup`) to setup the window. Every launch triggers the activate event (`connect_activate`). Right now it does nothing so that sirula does not launch twice, but it could be used to show the hidden window.

How is the startup time for you, if you don't load any entries? Because my idea was to load the entries asynchronously.

**Comment by The0x539** [comment]
Measuring from the top of `main` to the bottom of `app_startup`, replacing line 93 of main.rs with `Default::default()` seems to take me from about 192ms to about 152ms. It's an improvement, but not enough on its own.

**Pull request merged**
